/*
 * This software is in the public domain under CC0 1.0 Universal plus a
 * Grant of Patent License.
 */

apply plugin: 'groovy'

def componentNode = parseComponent(project)
version = componentNode.'@version'
def jarBaseName = componentNode.'@name'
def moquiDir = projectDir.parentFile.parentFile.parentFile
def frameworkDir = file(moquiDir.absolutePath + '/framework')

repositories {
    flatDir name: 'localLib', dirs: frameworkDir.absolutePath + '/lib'
    mavenCentral()
}

tasks.withType(JavaCompile) { options.compilerArgs << "-proc:none" }
tasks.withType(GroovyCompile) { options.compilerArgs << "-proc:none" }

dependencies {
    implementation project(':framework')
    runtimeOnly 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    testImplementation project(':framework').configurations.testImplementation.allDependencies
}

check.dependsOn.clear()

test {
    useJUnitPlatform()
    testLogging { events "passed", "skipped", "failed" }
    testLogging.showStandardStreams = true
}

task cleanLib(type: Delete) { delete fileTree(dir: projectDir.absolutePath + '/lib', include: '*') }
clean.dependsOn cleanLib

jar {
    destinationDirectory = file(projectDir.absolutePath + '/lib')
    archiveBaseName = jarBaseName
}

tasks.register('copyDependencies', Copy) {
    dependsOn cleanLib
    from (configurations.runtimeClasspath -
            project(':framework').configurations.runtimeClasspath -
            project(':framework').tasks.named('jar').get().archiveFile.get().asFile)
    into file(projectDir.absolutePath + '/lib')
}

jar.dependsOn copyDependencies
